### PR TITLE
support worktrees

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by taq** [comment]
Thanks! But now we have more efficient ways to show the branches on Vim, so I'm not maintaining this too much. :-)

**Comment by mathstuf** [comment]
I know; I still use this though (maybe I should try the fugitive one again, but I think it expected you to patch your font or something). Which one do you use?

**Comment by taq** [comment]
Also fugitive. :-)

**Comment by mathstuf** [comment]
Ah, fugitive doesn't show available branches. That's why I still use this one :) .

**Pull request merged**
